ENV_DB_USERNAME_KEY = "DB_USERNAME"
ENV_DB_PASSWORD_KEY = "DB_PASSWORD"
ENV_DB_ADDRESS_KEY = "DB_ADDRESS"
ENV_DB_PORT_KEY = "DB_PORT"
ENV_DB_NAME_KEY = "DB_NAME"

# TAB CONSTANTS
MAIN_FUNC_TAB_NAME = "เมนูหลัก"
DAILY_VACCINE_REPORT_TAB_NAME = "รายงานการฉีดวัคซีนรายวัน" 
DAILY_SEPARATE_REPORT_TAB_NAME = "รายงานการฉีดวัคซีนแยกยี่ห้อ"
WEEKLY_PERSON_VAC_REPORT_TAB_NAME = "รายงานการฉีดวัคซีนตามกลุ่มเป้าหมาย (ส่งผลรายสัปดาห์)"
FINANCIAL_REPORT_TAB_NAME = "รายงานส่งการเงิน"
FOREIGN_NON_THAI_REPORT_TAB_NAME = "คัดต่างด้าวและบุคคลไม่มีสถานะ"
SETTING_TAB_NAME = "การตั้งค่า"
PERSON_TYPE_SETTING_TAB_NAME = "กลุ่มเป้าหมายตาม MOPH-IC"
